# Generated by Django 4.1.3 on 2022-12-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=128, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
