# Generated by Django 4.1.3 on 2022-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danny', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
    ]
